export enum TableDetail {
  RANK = 'RANK',
  NAME = 'NAME',
  DISCOVERED_ON = 'DISCOVERED_ON',
  LAST_RANK = 'LAST_RANK',
  // TRADING_VOLUME_PERCENTAGE = 'TRADING_VOLUME_PERCENTAGE',
  // PRICE_CHANGE_PERCENTAGE = 'PRICE_CHANGE_PERCENTAGE',
  // PRICE = 'PRICE',
  // VOLUME = 'VOLUME',
  CURRENT_PRICE = 'CURRENT_PRICE',
  CURRENT_VOLUME_24H = 'CURRENT_VOLUME_24H',
  CURRENT_MARKET_CAP = 'CURRENT_MARKET_CAP',
  CURRENT_NUMBER_HOLDERS = 'CURRENT_NUMBER_HOLDERS',
  CURRENT_PRICE_CHANGE_PERCENTAGE_24H = 'CURRENT_PRICE_CHANGE_PERCENTAGE_24H',

  PREDICTED_PRICE = 'PREDICTED_PRICE',
  PREDICTED_VOLUME_24H = 'PREDICTED_VOLUME_24H',
  PREDICTED_MARKET_CAP = 'PREDICTED_MARKET_CAP',
  PREDICTED_NUMBER_HOLDERS = 'PREDICTED_NUMBER_HOLDERS',
  PREDICTED_PRICE_CHANGE_PERCENTAGE_24H = 'PREDICTED_PRICE_CHANGE_PERCENTAGE_24H',

  PRICE_CHANGE_PERCENTAGE_FROM_PREDICTED = 'PRICE_CHANGE_PERCENTAGE_FROM_PREDICTED',
  VOLUME_CHANGE_PERCENTAGE__FROM_PREDICTED = 'VOLUME_CHANGE_PERCENTAGE_FROM_PREDICTED',

  ACTION = 'ACTION',
}

export enum TokenStatus {
  NEW_DISCOVERED = 'NEW_DISCOVERED',
  PREVIOUS_PREDICTED = 'PREVIOUS_PREDICTED',
  NEXT_PREDICTED = 'NEXT_PREDICTED',
  DISCOVERED_DATE_CHANGE = 'DISCOVERED_DATE_CHANGE',
}

export enum SortDirection {
  ASC = 'ASC',
  DESC = 'DESC',
}

export enum LayoutMode {
  TABLE_LARGE,
  TABLE_WITH_DETAILS,
}

export enum ComPonentAllocation {
  TRENDING_SOON_TABLE_LARGE,
  TRENDING_SOON_TABLE_WITH_DETAILS,
  TRENDING_TABLE_LARGE,
  TRENDING_TABLE_WITH_DETAILS,
  HISTORICAL_TABLE_LARGE,
  HISTORICAL_TABLE_WITH_DETAILS,
  HISTORICAL_DETAILS_TABLE_LARGE,
  HISTORICAL_DETAILS_TABLE_WITH_DETAILS,
}

export const COMPARE_ITEM_PER_PAGE = 20
export const COMPARE_MAX_ITEMS = 60
export interface PredictedDate {
  mediumDate: number
  firstDate: number
  index: number
}

export interface ChartDisplaySettings {
  showPredictedDate: boolean
  showRanking: boolean
}
