export enum TableDetail {
  RANK = 'RANK',
  NAME = 'NAME',
  DISCOVERED_ON = 'DISCOVERED_ON',
  LAST_RANK = 'LAST_RANK',
  // TRADING_VOLUME_PERCENTAGE = 'TRADING_VOLUME_PERCENTAGE',
  // PRICE_CHANGE_PERCENTAGE = 'PRICE_CHANGE_PERCENTAGE',
  // PRICE = 'PRICE',
  // VOLUME = 'VOLUME',
  CURRENT_PRICE = 'CURRENT_PRICE',
  CURRENT_VOLUME_24H = 'CURRENT_VOLUME_24H',
  CURRENT_MARKET_CAP = 'CURRENT_MARKET_CAP',
  CURRENT_NUMBER_HOLDERS = 'CURRENT_NUMBER_HOLDERS',
  CURRENT_PRICE_CHANGE_PERCENTAGE_24H = 'CURRENT_PRICE_CHANGE_PERCENTAGE_24H',

  PREDICTED_PRICE = 'PREDICTED_PRICE',
  PREDICTED_VOLUME_24H = 'PREDICTED_VOLUME_24H',
  PREDICTED_MARKET_CAP = 'PREDICTED_MARKET_CAP',
  PREDICTED_NUMBER_HOLDERS = 'PREDICTED_NUMBER_HOLDERS',
  PREDICTED_PRICE_CHANGE_PERCENTAGE_24H = 'PREDICTED_PRICE_CHANGE_PERCENTAGE_24H',

  PRICE_CHANGE_PERCENTAGE_FROM_PREDICTED = 'PRICE_CHANGE_PERCENTAGE_FROM_PREDICTED',
  VOLUME_CHANGE_PERCENTAGE__FROM_PREDICTED = 'VOLUME_CHANGE_PERCENTAGE_FROM_PREDICTED',
}

export enum TokenStatus {
  NEW_DISCOVER = 'NEW_DISCOVER',
  CHANGE_DISCOVER = 'CHANGE_DISCOVER',
  PREVIOUS_PREDICT = 'PREVIOUS_PREDICT',
  NEXT_PREDICT = 'NEXT_PREDICT',
}

export enum SortDirection {
  ASC = 'ASC',
  DESC = 'DESC',
}

export enum LayoutMode {
  TABLE_LARGE,
  TABLE_WITH_DETAILS,
}

export enum ComPonentAllocation {
  TRENDING_SOON_TABLE_LARGE,
  TRENDING_SOON_TABLE_WITH_DETAILS,
  TRENDING_TABLE_LARGE,
  TRENDING_TABLE_WITH_DETAILS,
  HISTORICAL_TABLE_LARGE,
  HISTORICAL_TABLE_WITH_DETAILS,
  HISTORICAL_DETAILS_TABLE_LARGE,
  HISTORICAL_DETAILS_TABLE_WITH_DETAILS,
}
